'use client'

import Image from "next/image";
import NavBar from "./components/Navbar";

import { AnimatePresence } from "framer-motion";
import NeueHaasGrotesk from "./NeueHaasGroteskFont";

import Curve from "./components/Layout/Curve/index";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>SBU KCF</title>
        <meta property="og:title" content="SBU KCF" key="title" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" sizes="any" />
      </Head>
      <Curve backgroundColor="#222428">
        <main className="bg-[#222428] text-[#fefbf5]">

          <NavBar />
          <div className="w-full min-h-[calc(100vh-4rem)] h-full flex flex-col justify-end items-center">
            {/* LOGO START */}
            <div className="w-full flex flex-row justify-between items-start px-[4rem] m-0 p-0 select-none">
              <div className="m-0 p-0 overflow-hidden inline-block align-text- space-x-[2.5rem]">
                <span className="times-new-roman text-[#fefbf5] text-[24vw] font-normal lowercase italic overflow-hidden">SBU</span>
                <span className="eb-garamond text-[#fefbf5] text-[24vw] font-normal lowercase overflow-hidden">KCF</span>
              </div>

              <div className="relative w-[20vw]">
                <Image className={"text-[#fefbf5]"} src={"/icon.svg"} width={0} height={0} sizes="100vw" style={{ width: "100%", height: "auto" }} alt={""} priority={true} quality={100} />
              </div>
            </div>
            {/* LOGO END */}
          </div>

          {/* Eyecatcher here... */}

          {/* little about section here */}
          <div className="w-full h-[50vh] text-left text-[45px] font-[500] tracking-[1.5px] leading-[125%] p-[2rem] flex flex-row justify-evenly items-start">
            <h1 className={"font-neueHaasGrotesk tracking-[3px]"}>Upcoming Events</h1>
            <div className="flex flex-row justify-center items-center space-x-[3rem]">
              <div className="w-[20rem] h-[25rem] bg-[#d0cfcc] rounded-[15px]"></div>
              <div className="w-[20rem] h-[25rem] bg-[#d0cfcc] rounded-[15px]"></div>
              <div className="w-[20rem] h-[25rem] bg-[#d0cfcc] rounded-[15px]"></div>
            </div>

          </div>

        </main>
      </Curve>
    </>
  );
}